/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package act3;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author cesar
 */
public class Interfaz extends javax.swing.JFrame {

    
    public static int xc = -1,yc = -1,xf = 0,yf = 0;
    double r;
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        setLocation(400,200);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TimeBre1 = new javax.swing.JLabel();
        TimeBre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Centro Circulo ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("Cuerda Circulo  ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("DDA");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setText("Bresenham");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TimeBre1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TimeBre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addComponent(TimeBre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimeBre1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        
        if (xc == -1 && yc == -1){
            
            xc = evt.getX();
            yc = evt.getY();
            
            jLabel1.setText("("+xc+","+yc+")");
            jLabel2.setText("");
            
        }else{
            xf = evt.getX();
            yf = evt.getY();
            
            r = Math.sqrt(Math.pow(xf-xc, 2)+Math.pow(yf-yc,2));
            r = Math.abs(r);
            
            long startTime = System.nanoTime();
            BresenhamCircle(xc ,yc ,r );
            long endTime = System.nanoTime() - startTime;
            
            long startTime1 = System.nanoTime();
            MidPointCircle(xc ,yc ,r );
            long endTime1 = System.nanoTime() - startTime1;
            
            endTime =  endTime/1000000;
            endTime1 =  endTime1/1000000;
            
            TimeBre.setText(String.valueOf(endTime)+" Milisegundos");
            TimeBre1.setText(String.valueOf(endTime1)+" Milisegundos");
            
            jLabel2.setText("("+xf+","+yf+")");
            xc = -1;
            yc = -1;
        }
        
    }//GEN-LAST:event_jPanel1MouseClicked

    public void BresenhamCircle(int xc, int yc, double r){
        int color = 0;
        int d = (int) (3 - 2 * r);
        int p = 0, q = (int) r; 
        
        drawCircle(xc, yc, p, q, color); 
        while (p <= q) 
        { 
            p++; 
            if (d < 0) 
            { 
                d = d + 4 * p + 6;
            } 
            else{
                q--;  
                d = d + 4 * (p - q) + 10; 
            }
            drawCircle(xc, yc, p, q, color);
        } 
    }
    
    public void MidPointCircle(int xc,  int yc, double r)  
    { 
        int x = (int) r, y = 0; 
        int P = (int) (1 - r);
        int color = 1;
        
        drawCircle(xc, yc, x, y, color);
        
        while (x > y) { 
            y++;
            if (P <= 0) 
                P = P + 2 * y + 1; 
            else { 
                x--; 
                P = P + 2 * y - 2 * x + 1; 
            } 
            if (x < y) 
                break; 
            drawCircle(xc, yc, x, y, color); 
        } 
    } 

    public void drawCircle(int xc, int yc, int p, int q, int color) 
    { 
        Graphics g = getGraphics();
        if(color == 1){
            g.setColor(Color.BLUE);
        }else{
            g.setColor(Color.RED);
        }
        g.fillRect(xc+p+140, yc+q+30, 2, 2);
        g.fillRect(xc-p+140, yc+q+30, 2, 2);
        g.fillRect(xc+p+140, yc-q+30, 2, 2);
        g.fillRect(xc-p+140, yc-q+30, 2, 2);
        g.fillRect(xc+q+140, yc+p+30, 2, 2);
        g.fillRect(xc-q+140, yc+p+30, 2, 2);
        g.fillRect(xc+q+140, yc-p+30, 2, 2);
        g.fillRect(xc-q+140, yc-p+30, 2, 2); 
    }
    
    public void drawLine(int xc, int yc, int p, int q, int color) 
    { 
        Graphics g = getGraphics();
        if(color == 1){
            g.setColor(Color.BLUE);
        }else{
            g.setColor(Color.RED);
        }
        g.drawLine(xc+p+140, yc+q+30, 2, 2);
        g.drawLine(xc-p+140, yc+q+30, 2, 2);
        g.drawLine(xc+p+140, yc-q+30, 2, 2);
        g.drawLine(xc-p+140, yc-q+30, 2, 2);
        g.drawLine(xc+q+140, yc+p+30, 2, 2);
        g.drawLine(xc-q+140, yc+p+30, 2, 2);
        g.drawLine(xc+q+140, yc-p+30, 2, 2);
        g.drawLine(xc-q+140, yc-p+30, 2, 2); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TimeBre;
    private javax.swing.JLabel TimeBre1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}